[project]
name = "scrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lbc>=1.1.2",
    "playwright>=1.42.0",
    "playwright-stealth>=1.0.6",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
